# Generated by Django 5.2.6 on 2025-09-16 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='hide_name',
            field=models.BooleanField(default=False),
        ),
    ]
