# Generated by Django 5.2.6 on 2025-09-17 12:57

import django.db.models.deletion
import main_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_location_tag_remove_memory_tags_dailydiary_locations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailydiary',
            name='photo',
        ),
        migrations.CreateModel(
            name='DiaryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=main_app.models.diary_file_path)),
                ('diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='main_app.dailydiary')),
            ],
        ),
    ]
