# Generated by Django 5.2.6 on 2025-09-18 00:17

import main_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_remove_dailydiary_photo_diaryphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailydiary',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=main_app.models.diary_file_path),
        ),
        migrations.DeleteModel(
            name='DiaryPhoto',
        ),
    ]
